module.exports = {
  'Forgot password': {
    templateName: 'changePassword',
    subject: 'change password',
  },
  'Your generated password': {
    templateName: 'autoGeneratedPassword',
    subject: 'new password',
  },
};
