version: '3'

services:
  database-server:
    image: 'postgres'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: magical_password
      POSTGRES_DB: postgres
    ports:
      - '5434:5432'
    volumes:
      - database-data-server:/var/lib/postgresql/data/

volumes:
  database-data-server:
